tasks:
  - name: Setup Working Environment
    openMode: split-left
    init: |
      yarn install
    command: yarn dev

ports:
  - port: 3000
    onOpen: open-preview
    name: Dev Preview

# Configure vscode
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ecmel.vscode-html-css
    - Equinusocio.vsc-community-material-theme
    - EditorConfig.EditorConfig
    - streetsidesoftware.code-spell-checker
    - Vue.volar
    - GraphQL.vscode-graphql
    - christian-kohler.npm-intellisense
    - eamodio.gitlens
    - atlassian.atlascode
    - amazonwebservices.aws-toolkit-vscode
    - SonarSource.sonarlint-vscode
    - ZixuanChen.vitest-explorer
    - bradlc.vscode-tailwindcss
    - adpyke.codesnap
    - dbaeumer.vscode-eslint
    - gamunu.vscode-yarn
    
jetbrains:
  webstorm:
    prebuilds:
      version: both
    
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: prevent-merge-on-error
    addComment: true
